---
- hosts: localhost
  become: yes
  tasks: 
  - name: install httpd on redhat
    yum: 
     name: httpd
     state: present
    when: ansible_os_family == "Redhat"
    tags:
      - install
  - name: install  apache2 on ubuntu
    apt: 
     name: apache2
     state: present
    when: ansible_os_family == "Debian"
    tags:
      - install 
      - service 
  - name: Print free memory
    debug:
      msg: "free memory is {{ ansible_memory_mb.real.free}}"
    tags:
      - debug

