---
- hosts: webserver
  tasks: 
  - name: install java
    yum:
      name: java-1.8.0-openjdk.x86_64
      state: present
  - name: tomcat install   
    yum:
      name: tomcat
      state: present
  - name: downlaod the jenkins 
    get_url:
      url: https://ftp.yz.yamagata-u.ac.jp/pub/misc/jenkins/war-stable/2.60.2/jenkins.war
      dest: /usr/share/tomcat/webapps/jenkins.war
  - name: enable and start tomcat service 
    service:
      name: tomcat
      state: started 
      enabled: yes  
