---
- hosts: localhost
  connection: ssh
  pre_tasks:
  - name: When did the Role start
    raw: date > /home/ansible/start.log
  roles:
    - handlers
  post_tasks:
  - name: when did the role end 
    raw: date > /home/ansible/stop.log

