---
- hosts: all
  become: yes
  tasks:
  - name: install webserver
    yum:
      name:  httpd
      state: present
    when: ansible_os_family == 'RedHat'
  - name: install webserver in ubuntu
    apt: 
      name: apache2
      state: present
    when: ansible_os_family == 'Debian' 
