---
- hosts: localhost 
  tasks: 
   - name: install httpd packakeges in Redhat 
     yum:
       name: httpd
       state: installed
     when: ansible_os_family == 'Redhat'
     tags: 
       - redhat install
   - name: install appache2 on ubuntu
     apt:
       name: apache2
       state: installed
     when: ansible_os_family == 'Debian' 
     tags:
       - ubuntu install
   - name: restart httpd
     service:
       name: httpd
       state: restarted
     when: ansible_os_family == 'Redhat'
   - name: restart apache2
     service:
       name: apache2
       state: restarted
     when: ansible_os_family == 'Debian'
   - name: copy the home page 
     template:
       src:  html.j2
       dest: /var/www/html/index.html
     notify: restart httpd
  handlers:
   - name: restart httpd
     service: 
       name: httpd 
       state: restarted
