- name: install httpd
  yum: pkg=httpd state=latest
  when: "ansible_os_family == 'RedHat'"
  ignore_errors: yes
- name: install apache2
  apt: pkg=apache2 state=latest
  when: "ansible_os-family == 'Debian'"
  ignore_errors: yes
